version: "3.7"
services:
  django:
    image: python:3
    volumes:
      - "./rblog/:/app/"
    working_dir: /app
    environment:
      - SECRET_KEY=example_secret_key
      - BOT_NAME=bot
      - BOT_PASS=botpassword
      - CHALLENGE_FLAG=flag{test_qwq}
    command: bash /app/run.sh
  nginx:
    image: nginx
    ports:
      - "65480:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./rblog.conf:/etc/nginx/conf.d/default.conf"
      - "./rblog/static/:/app/static/"
